language: php
php:
  - nightly
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

sudo: false

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --dev --no-interaction

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

script:
  - ./vendor/bin/phpunit -v --configuration phpunit.xml --coverage-text
